### ISSUE TITLE
crash on dedicated server running all the mods 9 on forge 1.20.1 47.1.0

### ISSUE THREAD

**Issue by thiccmeme** [PandaDap2006/Pandas-Falling-Trees#17]
this is just the relavant part of a recent log, running all the mods 9 on 1.20.1 version 47.1.0

[12Jul2023 04:46:31.154] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'boolean me.pandadev.fallingtrees.tree.TreeUtils.shouldTreeFall(net.minecraft.core.BlockPos, net.minecraft.world.level.Level, net.minecraft.world.entity.player.Player)'
	at me.pandadev.fallingtrees.tree.TreeCache.createCache(TreeCache.java:49) ~[fallingtrees-1.19.3-1.20.1+0.5.2-beta.jar%23424!/:?]
	at me.pandadev.fallingtrees.tree.TreeCache.getOrCreateCache(TreeCache.java:44) ~[fallingtrees-1.19.3-1.20.1+0.5.2-beta.jar%23424!/:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.handler$bgb000$getDestroyProgress(MixinBlockStateBase.java:2972) ~[server-1.20.1-20230612.114412-srg.jar%23575!/:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60625_(MixinBlockStateBase.java:641) ~[server-1.20.1-20230612.114412-srg.jar%23575!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_214168_(ServerPlayerGameMode.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23575!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7502_(ServerGamePacketListenerImpl.java:1018) ~[server-1.20.1-20230612.114412-srg.jar%23575!/:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:42) ~[server-1.20.1-20230612.114412-srg.jar%23575!/:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:8) ~[server-1.20.1-20230612.114412-srg.jar%23575!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[server-1.20.1-20230612.114412-srg.jar%23575!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23575!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23575!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23575!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770) ~[server-1.20.1-20230612.114412-srg.jar%23575!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23575!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23575!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753) ~[server-1.20.1-20230612.114412-srg.jar%23575!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23575!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[server-1.20.1-20230612.114412-srg.jar%23575!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:732) ~[server-1.20.1-20230612.114412-srg.jar%23575!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665) ~[server-1.20.1-20230612.114412-srg.jar%23575!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23575!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[12Jul2023 04:46:31.198] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 75fb780e-e412-49e2-8893-d7134f1b8d92
[12Jul2023 04:46:31.198] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: This crash report has been saved to: /home/minecraft/multicraft/servers/server510532/./crash-reports/crash-2023-07-12_04.46.31-server.txt
[12Jul2023 04:46:31.198] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
[12Jul2023 04:46:31.199] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving players

**Comment by PandaDap2006** [comment]
im sorry about that, this is my mistake, i made a function used by the server only be available on the client. i will fix this.

**Comment by PandaDap2006** [comment]
this has been fixed in the latest update.
