### ISSUE TITLE
Unexpected Crash

### ISSUE THREAD

**Issue by Aabaddon** [PandaDap2006/Pandas-Falling-Trees#30]
Hey sorry to bother you, your mod is incredible and almost perfect but recently i have been experiencing some crashes when chopping down moded trees (from Lets do Vinery) something about a rendering error, ill paste it so you can look into it, thanks for making this mod.

[20:52:52] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering entity in world
	at net.minecraft.class_898.method_3954(class_898.java:176) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22977(class_761.java:1574) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1324) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:880) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1-0.14.22.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1920.method_23752(net.minecraft.class_2338, net.minecraft.class_6539)" because "$$0" is null
	at net.minecraft.class_1163.method_4965(class_1163.java:14) ~[client-intermediary.jar:?]
	at net.minecraft.class_1163.method_4966(class_1163.java:22) ~[client-intermediary.jar:?]
	at satisfyu.vinery.client.VineryClient.lambda$onInitializeClient$1(VineryClient.java:66) ~[letsdo-vinery-fabric-1.4.4.jar:?]
	at net.minecraft.class_324.method_1697(class_324.java:123) ~[client-intermediary.jar:?]
	at net.minecraft.class_776.method_3353(class_776.java:104) ~[client-intermediary.jar:?]
	at me.pandadev.fallingtrees.client.renderer.TreeRenderer.render(TreeRenderer.java:49) ~[fallingtrees-1.19.3-1.20.1+0.5.3-beta.jar:?]
	at me.pandadev.fallingtrees.client.renderer.TreeRenderer.method_3936(TreeRenderer.java:22) ~[fallingtrees-1.19.3-1.20.1+0.5.3-beta.jar:?]
	at net.minecraft.class_898.method_3954(class_898.java:145) ~[client-intermediary.jar:?]
	... 10 more

**Comment by PandaDap2006** [comment]
Thanks for the report, i will see if i can fix it.
Sorry for the late response, i was on vacation when you sent this.

**Comment by PandaDap2006** [comment]
Should hopefully be fixed.
