### ISSUE TITLE
Config seems broken

### ISSUE THREAD

**Issue by Proxwian** [PandaDap2006/Pandas-Falling-Trees#58]
Dynamic mining speed is not working
disableCrouchMining - broken
Only fall with required tool - broken

The only value that works for me is maxLogAmount

1.20.1 Forge 41.2.20 fallingtrees-0.11-forge-1.20.jar

**Comment by PandaDap2006** [comment]
I will check out why this isn't working and make a patch

**Comment by Proxwian** [comment]
```

[00:05:42] [Server thread/ERROR] [net.minecraft.network.protocol.PacketUtils]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundPlayerActionPacket@56cfa9ba, suppressing error
java.lang.NullPointerException: Cannot read field "invertCrouchMining" because the return value of "me.pandamods.fallingtrees.config.FallingTreesConfig.getClientConfig(net.minecraft.world.entity.player.Player)" is null
	at me.pandamods.fallingtrees.trees.StandardTree.allowedToFall(StandardTree.java:123) ~[fallingtrees-0.11-forge-1.20.jar%23385!/:?]
	at me.pandamods.fallingtrees.event.EventHandler.makeTreeFall(EventHandler.java:50) ~[fallingtrees-0.11-forge-1.20.jar%23385!/:?]
	at me.pandamods.fallingtrees.event.EventHandler.lambda$makeTreeFall$0(EventHandler.java:42) ~[fallingtrees-0.11-forge-1.20.jar%23385!/:?]
	at java.util.Optional.filter(Optional.java:218) ~[?:?]
	at me.pandamods.fallingtrees.event.EventHandler.makeTreeFall(EventHandler.java:42) ~[fallingtrees-0.11-forge-1.20.jar%23385!/:?]
	at me.pandamods.fallingtrees.event.EventHandler.onBlockBreak(EventHandler.java:34) ~[fallingtrees-0.11-forge-1.20.jar%23385!/:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53) ~[architectury-9.2.14-forge.jar%23346!/:?]
	at dev.architectury.event.EventFactory$2.handleInvocation(EventFactory.java:81) ~[architectury-9.2.14-forge.jar%23346!/:?]
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87) ~[guava-31.1-jre.jar%23147!/:?]
	at jdk.proxy3.$Proxy183.breakBlock(Unknown Source) ~[?:?]
	at dev.architectury.event.forge.EventHandlerImplCommon.event(EventHandlerImplCommon.java:369) ~[architectury-9.2.14-forge.jar%23346!/:?]
	at dev.architectury.event.forge.__EventHandlerImplCommon_event_BreakEvent.invoke(.dynamic) ~[architectury-9.2.14-forge.jar%23346!/:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23145!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:319) ~[eventbus-6.0.5.jar%23145!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:299) ~[eventbus-6.0.5.jar%23145!/:?]
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:556) ~[forge-1.20.1-47.2.20-universal.jar%23477!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_9280_(ServerPlayerGameMode.java:319) ~[server-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_215116_(ServerPlayerGameMode.java:305) ~[server-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_214168_(ServerPlayerGameMode.java:273) ~[server-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7502_(ServerGamePacketListenerImpl.java:1494) ~[server-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:42) ~[server-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:8) ~[server-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:25) ~[server-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:1027) ~[server-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:173) ~[server-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:1010) ~[server-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:1004) ~[server-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[server-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:990) ~[server-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:906) ~[server-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by Proxwian** [comment]
Hope this can help
